# Generated by Django 3.2.6 on 2021-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='contact_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='admin'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='seller'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='customer'),
        ),
    ]
