# Generated by Django 3.2.6 on 2021-09-01 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_shopping', '0006_auto_20210901_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='CustomerProfile',
        ),
    ]
