# Generated by Django 3.2.6 on 2021-09-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0008_category_feedback_inquiry_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='Select Subcategory', on_delete=django.db.models.deletion.CASCADE, to='online_shopping.category'),
        ),
    ]
