# Generated by Django 3.2.6 on 2021-09-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0009_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
