# Generated by Django 3.2.6 on 2021-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0010_auto_20210902_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='contact_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
