# Generated by Django 3.2.6 on 2021-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0011_alter_adminprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='admin'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='seller'),
        ),
    ]
