# Generated by Django 3.2.6 on 2021-09-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0012_auto_20210903_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
