# Generated by Django 3.2.6 on 2021-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0014_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
